# Generated by Django 3.0 on 2023-09-10 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob', models.CharField(choices=[('P', 'select your problem'), ('L', 'leg and Hand pain'), ('N', 'neck and Back pain'), ('H', 'cheast pain'), ('HEAD', 'head pain'), ('S', 'stomach pain'), ('G', 'Sex problem')], default='P', max_length=50)),
                ('desc_of_problem', models.TextField()),
                ('date_of_occurrence', models.DateField()),
                ('problem_status', models.CharField(choices=[('Success', 'Success'), ('Pending', 'Pending')], default='Pending', max_length=50)),
                ('patient_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.PatientProfile')),
            ],
        ),
    ]
