# Generated by Django 3.0 on 2023-09-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20230910_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='prob',
            field=models.CharField(choices=[('P', 'select your problem'), ('Orthopaedics', 'leg and Hand pain'), ('Orthopaedics', 'neck and Back pain'), ('Cardiology', 'chest pain'), ('Neurology', 'head pain'), ('Stomach', 'stomach pain'), ('ENT', 'cough and cold and ear')], default='P', max_length=50),
        ),
    ]
