# Generated by Django 3.0 on 2023-09-10 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20230910_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='patient_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
