# Generated by Django 3.0 on 2023-09-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_auto_20230912_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='req_date',
            field=models.DateField(auto_now=True),
        ),
    ]
