# Generated by Django 3.0 on 2023-09-18 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_doctorprofile_patients'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_text', models.TextField()),
                ('solution_date', models.DateField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.DoctorProfile')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Problem')),
            ],
        ),
    ]
